<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="MailKit" Version="4.15.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>


	<ItemGroup>
	  <ProjectReference Include="..\JuanApp.BLL\JuanApp.BLL.csproj" />
	</ItemGroup>


	<ItemGroup>
	  <_ContentIncludedByDefault Remove="Views\Product\Detail.cshtml" />
	  <_ContentIncludedByDefault Remove="wwwroot\uploads\products\29c5ba13-0c67-4574-a648-825490219666_IMDb DBDesigner.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\uploads\products\42509087-c292-4a8b-bb93-e52f312e73fb_TurboAz DBDesigner.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\uploads\products\8ce0a496-d416-48d0-9001-5756fa8f2a64_Spotify DBDesigner.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\uploads\products\b1169356-411e-46f5-a225-1250c98176e7_Spotify DBDesigner.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\uploads\products\b7650ac8-f49a-4389-a625-faddd92e2138_ERDDBMS.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\uploads\products\f001ef74-730a-46a9-ba71-1a3177616315_3Division.png" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Advantage\Create.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Advantage\Edit.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Advantage\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Auth\Login.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Blog\Create.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Blog\Edit.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Blog\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Category\Create.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Category\Edit.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Category\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Color\Create.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Color\Edit.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Color\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Dashboard\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Order\Details.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Order\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Product\Create.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Product\Edit.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Product\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Settings\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Shared\_Layout.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Size\Create.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Size\Edit.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Size\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Slider\Create.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Slider\Edit.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Slider\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\Subscriber\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\_ViewImports.cshtml" />
	  <_ContentIncludedByDefault Remove="Areas\Admin\Views\_ViewStart.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Account\ForgotPassword.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Account\Login.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Account\Profile.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Account\Register.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Account\ResetPassword.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Basket\Checkout.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Basket\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Blog\Details.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Blog\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Home\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Product\Details.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Shared\_Layout.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Shared\_ProductModalPartial.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Shared\_ValidationScriptsPartial.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\Shop\Index.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\_ViewImports.cshtml" />
	  <_ContentIncludedByDefault Remove="Views\_ViewStart.cshtml" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\admin\css\admin.css" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\admin\js\admin.js" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\css\custom.css" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\css\images\ui-icons_444444_256x240.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\css\images\ui-icons_555555_256x240.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\css\images\ui-icons_777620_256x240.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\css\images\ui-icons_777777_256x240.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\css\images\ui-icons_cc0000_256x240.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\css\images\ui-icons_ffffff_256x240.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\css\plugins.css" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\css\style.css" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\css\vendor.css" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\fontawesome-webfont3e6e.eot" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\fontawesome-webfont3e6e.svg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\fontawesome-webfont3e6e.ttf" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\fontawesome-webfont3e6e.woff" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\fontawesome-webfont3e6e.woff2" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\fontawesome-webfontd41d.eot" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\ionicons28b5.eot" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\ionicons28b5.svg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\ionicons28b5.ttf" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\fonts\ionicons28b5.woff" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\about\avatar.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\about\services.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\banner\banner-1.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\banner\banner-2.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\banner\banner-3.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\banner\banner_left.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\blog\11.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\blog\blog-1.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\blog\blog-2.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\blog\blog-3.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\blog\blog-4.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\blog\blog-details-1.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\blog\blog-details-2.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\blog\comment-icon.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\blog\recent-01.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\blog\recent-02.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\blog\recent-03.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\blog\recent-04.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\brand\br1.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\brand\br2.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\brand\br3.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\brand\br4.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\brand\br5.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\cart\cart-1.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\cart\cart-2.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\favicon.ico" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\icon\cancel.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\icon\en.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\icon\fr.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\icon\policy-1.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\icon\policy-2.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\icon\policy-3.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\logo\logo.png" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\paypal-card.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\8ccf8bad-dfbb-4560-b48f-c1736978ef57_product-2.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\pro-small-1.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\pro-small-2.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\pro-small-3.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\pro-small-4.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-1.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-10.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-11.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-12.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-2.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-3.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-4.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-5.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-6.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-7.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-8.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-9.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-details-img1.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-details-img2.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-details-img3.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\product\product-details-img4.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\slider\slider-1.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\slider\slider-2.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\testimonial\tm-1.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\testimonial\tm-2.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\img\testimonial\tm-3.jpg" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\js\active.js" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\js\custom.js" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\js\main.js" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\js\modernizr-2.8.3.min.js" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\js\plugins.js" />
	  <_ContentIncludedByDefault Remove="wwwroot\assets\js\vendor.js" />
	  <_ContentIncludedByDefault Remove="wwwroot\EmailTemplates\EmailConfirmation.html" />
	  <_ContentIncludedByDefault Remove="wwwroot\EmailTemplates\NewProductEmail.html" />
	  <_ContentIncludedByDefault Remove="wwwroot\EmailTemplates\PasswordReset.html" />
	  <_ContentIncludedByDefault Remove="wwwroot\EmailTemplates\SubscribeEmail.html" />
	</ItemGroup>

</Project>
