// <auto-generated />
using JuanApp.DLL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuanApp.DLL.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220171056_mig_15")]
    partial class mig_15
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JuanApp.Core.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Key");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Key = "Logo",
                            Value = "logo.png"
                        },
                        new
                        {
                            Key = "ContactEmail",
                            Value = "myemail@gmail.com"
                        },
                        new
                        {
                            Key = "ContactPhone",
                            Value = "+ 00 123 254565"
                        },
                        new
                        {
                            Key = "Address",
                            Value = "1234 Street Name, City, Country"
                        },
                        new
                        {
                            Key = "FacebookUrl",
                            Value = "https://facebook.com/yourpage"
                        },
                        new
                        {
                            Key = "TwitterUrl",
                            Value = "https://twitter.com/yourprofile"
                        },
                        new
                        {
                            Key = "LinkedInUrl",
                            Value = "https://linkedin.com/in/yourprofile"
                        },
                        new
                        {
                            Key = "InstagramUrl",
                            Value = "https://instagram.com/yourprofile"
                        });
                });

            modelBuilder.Entity("JuanApp.Domain.Models.Advantage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Advantages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Building responsive and robust web applications.",
                            Icon = "policy-1.png",
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Creating user-friendly mobile applications.",
                            Icon = "policy-2.png",
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Scalable and secure cloud computing services.",
                            Icon = "policy-3.png",
                            Name = "Cloud Solutions"
                        });
                });

            modelBuilder.Entity("JuanApp.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Advanced smartwatch with health tracking features.",
                            DiscountPercentage = 10,
                            ImageUrl = "product-1.jpg",
                            InStock = true,
                            IsMain = true,
                            IsNew = false,
                            Name = "Smart Watch Pro",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Noise cancelling over-ear wireless headphones.",
                            DiscountPercentage = 15,
                            ImageUrl = "product-2.jpg",
                            InStock = true,
                            IsMain = true,
                            IsNew = false,
                            Name = "Wireless Headphones",
                            Price = 149.50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mechanical keyboard with RGB backlight.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-3.jpg",
                            InStock = true,
                            IsMain = true,
                            IsNew = false,
                            Name = "Gaming Keyboard",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Portable speaker with deep bass and clear sound.",
                            DiscountPercentage = 5,
                            ImageUrl = "product-4.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Bluetooth Speaker",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lightweight tracker for daily activity monitoring.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-5.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Fitness Tracker",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Multiport USB-C hub for modern laptops.",
                            DiscountPercentage = 20,
                            ImageUrl = "product-6.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "USB-C Hub",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Waterproof action camera for outdoor adventures.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-7.jpg",
                            InStock = false,
                            IsMain = false,
                            IsNew = true,
                            Name = "4K Action Camera",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ergonomic wireless mouse with long battery life.",
                            DiscountPercentage = 10,
                            ImageUrl = "product-8.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Wireless Mouse",
                            Price = 29.99m
                        });
                });

            modelBuilder.Entity("JuanApp.Domain.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 8
                        });
                });

            modelBuilder.Entity("JuanApp.Domain.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonLink")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ButtonText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ButtonLink = "/about",
                            ButtonText = "Learn More",
                            Description = "Your trusted partner in software solutions.",
                            ImageUrl = "slider-1.jpg",
                            IsMain = true,
                            SubTitle = "Quality Software Solutions",
                            Title = "Welcome to JuanApp"
                        },
                        new
                        {
                            Id = 2,
                            ButtonLink = "/services",
                            ButtonText = "Our Services",
                            Description = "Transforming ideas into reality.",
                            ImageUrl = "slider-2.jpg",
                            IsMain = true,
                            SubTitle = "Cutting-Edge Technology",
                            Title = "Innovative Solutions"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "banner-1.jpg",
                            IsMain = false,
                            SubTitle = "Stay Connected",
                            Title = "Join Our Community"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "banner-2.jpg",
                            IsMain = false,
                            SubTitle = "We're Here to Help",
                            Title = "Expert Support"
                        });
                });

            modelBuilder.Entity("JuanApp.Domain.Models.ProductImage", b =>
                {
                    b.HasOne("JuanApp.Domain.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JuanApp.Domain.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
