// <auto-generated />
using System;
using JuanApp.DLL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuanApp.DLL.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ColorProduct", b =>
                {
                    b.Property<int>("ColorsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("ColorsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ColorProduct", (string)null);
                });

            modelBuilder.Entity("JuanApp.Core.Models.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Baskets", (string)null);
                });

            modelBuilder.Entity("JuanApp.Core.Models.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("BasketItems", (string)null);
                });

            modelBuilder.Entity("JuanApp.Core.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Blogs", (string)null);
                });

            modelBuilder.Entity("JuanApp.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports & Outdoors"
                        });
                });

            modelBuilder.Entity("JuanApp.Core.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Colors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HexCode = "#FF0000",
                            Name = "Red"
                        },
                        new
                        {
                            Id = 2,
                            HexCode = "#0000FF",
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 3,
                            HexCode = "#00FF00",
                            Name = "Green"
                        },
                        new
                        {
                            Id = 4,
                            HexCode = "#FFFF00",
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 5,
                            HexCode = "#000000",
                            Name = "Black"
                        },
                        new
                        {
                            Id = 6,
                            HexCode = "#FFFFFF",
                            Name = "White"
                        });
                });

            modelBuilder.Entity("JuanApp.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("JuanApp.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedSize")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("JuanApp.Core.Models.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductReviews", (string)null);
                });

            modelBuilder.Entity("JuanApp.Core.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Key");

                    b.ToTable("Settings", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "Logo",
                            Value = "logo.png"
                        },
                        new
                        {
                            Key = "ContactEmail",
                            Value = "myemail@gmail.com"
                        },
                        new
                        {
                            Key = "ContactPhone",
                            Value = "+ 00 123 254565"
                        },
                        new
                        {
                            Key = "Address",
                            Value = "1234 Street Name, City, Country"
                        },
                        new
                        {
                            Key = "FacebookUrl",
                            Value = "https://facebook.com/yourpage"
                        },
                        new
                        {
                            Key = "TwitterUrl",
                            Value = "https://twitter.com/yourprofile"
                        },
                        new
                        {
                            Key = "LinkedInUrl",
                            Value = "https://linkedin.com/in/yourprofile"
                        },
                        new
                        {
                            Key = "InstagramUrl",
                            Value = "https://instagram.com/yourprofile"
                        });
                });

            modelBuilder.Entity("JuanApp.Core.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sizes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Small",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Large",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "X-Large",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "6",
                            SizeType = "Shoes"
                        },
                        new
                        {
                            Id = 6,
                            Name = "7",
                            SizeType = "Shoes"
                        },
                        new
                        {
                            Id = 7,
                            Name = "8",
                            SizeType = "Shoes"
                        },
                        new
                        {
                            Id = 8,
                            Name = "9",
                            SizeType = "Shoes"
                        });
                });

            modelBuilder.Entity("JuanApp.Core.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubscribedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subscribers", (string)null);
                });

            modelBuilder.Entity("JuanApp.Core.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New Arrival"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Best Seller"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Limited Edition"
                        },
                        new
                        {
                            Id = 4,
                            Name = "On Sale"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Exclusive"
                        });
                });

            modelBuilder.Entity("JuanApp.Domain.Models.Advantage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Advantages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Building responsive and robust web applications.",
                            Icon = "policy-1.png",
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Creating user-friendly mobile applications.",
                            Icon = "policy-2.png",
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Scalable and secure cloud computing services.",
                            Icon = "policy-3.png",
                            Name = "Cloud Solutions"
                        });
                });

            modelBuilder.Entity("JuanApp.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A timeless white t-shirt made from 100% cotton.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-1.jpg",
                            InStock = true,
                            IsMain = true,
                            IsNew = true,
                            Name = "Classic White T-Shirt",
                            Price = 19.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Comfortable blue denim jeans with a modern fit.",
                            DiscountPercentage = 10,
                            ImageUrl = "product-2.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = false,
                            Name = "Blue Denim Jeans",
                            Price = 49.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "A cozy red hoodie perfect for chilly days.",
                            DiscountPercentage = 5,
                            ImageUrl = "product-3.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Red Hoodie",
                            Price = 39.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Stylish black leather jacket for a bold look.",
                            DiscountPercentage = 15,
                            ImageUrl = "product-4.jpg",
                            InStock = false,
                            IsMain = true,
                            IsNew = false,
                            Name = "Black Leather Jacket",
                            Price = 99.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Casual green chinos made from breathable fabric.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-5.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Green Chinos",
                            Price = 44.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Description = "Lightweight yellow dress perfect for summer outings.",
                            DiscountPercentage = 20,
                            ImageUrl = "product-6.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = false,
                            Name = "Yellow Summer Dress",
                            Price = 59.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Comfortable gray sweatpants for lounging or workouts.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-7.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Gray Sweatpants",
                            Price = 29.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Elegant navy blue blazer suitable for formal occasions.",
                            DiscountPercentage = 10,
                            ImageUrl = "product-8.jpg",
                            InStock = false,
                            IsMain = true,
                            IsNew = false,
                            Name = "Navy Blue Blazer",
                            Price = 79.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Charming pink skirt with floral patterns.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-9.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Pink Floral Skirt",
                            Price = 34.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            Description = "Durable brown ankle boots for everyday wear.",
                            DiscountPercentage = 15,
                            ImageUrl = "product-10.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = false,
                            Name = "Brown Ankle Boots",
                            Price = 89.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Description = "Classic white sneakers that go with any outfit.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-11.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "White Sneakers",
                            Price = 59.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Description = "Sleek black formal shoes for special occasions.",
                            DiscountPercentage = 20,
                            ImageUrl = "product-12.jpg",
                            InStock = false,
                            IsMain = true,
                            IsNew = false,
                            Name = "Black Formal Shoes",
                            Price = 99.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Breathable orange t-shirt designed for sports activities.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-13.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Orange Sports T-Shirt",
                            Price = 24.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Lightweight shorts perfect for running and workouts.",
                            DiscountPercentage = 5,
                            ImageUrl = "product-14.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Green Running Shorts",
                            Price = 19.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Durable gloves for weightlifting and fitness training.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-15.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Black Fitness Gloves",
                            Price = 15.50m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Non-slip yoga mat for indoor and outdoor exercises.",
                            DiscountPercentage = 10,
                            ImageUrl = "product-16.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Blue Yoga Mat",
                            Price = 35.00m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Spacious gym bag with multiple compartments.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-17.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = false,
                            Name = "Red Gym Bag",
                            Price = 45.00m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Comfortable sneakers suitable for daily wear.",
                            DiscountPercentage = 15,
                            ImageUrl = "product-18.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "White Sneakers",
                            Price = 75.00m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Soft cotton hoodie with a minimalist design.",
                            DiscountPercentage = 5,
                            ImageUrl = "product-19.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = false,
                            Name = "Black Hoodie",
                            Price = 55.00m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Comfortable sweatpants for lounging or workouts.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-20.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = false,
                            Name = "Gray Sweatpants",
                            Price = 40.00m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Description = "Supportive sports bra for high-intensity workouts.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-21.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Pink Sports Bra",
                            Price = 30.00m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            Description = "Lightweight shoes designed for running efficiency.",
                            DiscountPercentage = 10,
                            ImageUrl = "product-22.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Navy Running Shoes",
                            Price = 85.00m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            Description = "Adjustable sports cap to keep the sun away.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-23.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Yellow Cap",
                            Price = 12.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            Description = "Elastic headband for fitness and running.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-24.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Purple Headband",
                            Price = 7.99m,
                            SalesCount = 0
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Description = "Reusable sports bottle with 1L capacity.",
                            DiscountPercentage = 0,
                            ImageUrl = "product-25.jpg",
                            InStock = true,
                            IsMain = false,
                            IsNew = true,
                            Name = "Orange Water Bottle",
                            Price = 14.99m,
                            SalesCount = 0
                        });
                });

            modelBuilder.Entity("JuanApp.Domain.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "product-details-img1.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "product-details-img2.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "product-details-img3.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "product-details-img4.jpg",
                            ProductId = 8
                        });
                });

            modelBuilder.Entity("JuanApp.Domain.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonLink")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ButtonText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Sliders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ButtonLink = "/about",
                            ButtonText = "Learn More",
                            Description = "Your trusted partner in software solutions.",
                            ImageUrl = "slider-1.jpg",
                            IsMain = true,
                            SubTitle = "Quality Software Solutions",
                            Title = "Welcome to JuanApp"
                        },
                        new
                        {
                            Id = 2,
                            ButtonLink = "/services",
                            ButtonText = "Our Services",
                            Description = "Transforming ideas into reality.",
                            ImageUrl = "slider-2.jpg",
                            IsMain = true,
                            SubTitle = "Cutting-Edge Technology",
                            Title = "Innovative Solutions"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "banner-1.jpg",
                            IsMain = false,
                            SubTitle = "Stay Connected",
                            Title = "Join Our Community"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "banner-2.jpg",
                            IsMain = false,
                            SubTitle = "We're Here to Help",
                            Title = "Expert Support"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductSize", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("SizesId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "SizesId");

                    b.HasIndex("SizesId");

                    b.ToTable("ProductSize", (string)null);
                });

            modelBuilder.Entity("ProductTag", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductTag", (string)null);
                });

            modelBuilder.Entity("ColorProduct", b =>
                {
                    b.HasOne("JuanApp.Core.Models.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanApp.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JuanApp.Core.Models.Basket", b =>
                {
                    b.HasOne("AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JuanApp.Core.Models.BasketItem", b =>
                {
                    b.HasOne("JuanApp.Core.Models.Basket", "Basket")
                        .WithMany("BasketItems")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanApp.Core.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("JuanApp.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanApp.Core.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId");

                    b.Navigation("Basket");

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("JuanApp.Core.Models.Order", b =>
                {
                    b.HasOne("AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JuanApp.Core.Models.OrderItem", b =>
                {
                    b.HasOne("JuanApp.Core.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanApp.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JuanApp.Core.Models.ProductReview", b =>
                {
                    b.HasOne("JuanApp.Domain.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JuanApp.Domain.Models.Product", b =>
                {
                    b.HasOne("JuanApp.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JuanApp.Domain.Models.ProductImage", b =>
                {
                    b.HasOne("JuanApp.Domain.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductSize", b =>
                {
                    b.HasOne("JuanApp.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanApp.Core.Models.Size", null)
                        .WithMany()
                        .HasForeignKey("SizesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductTag", b =>
                {
                    b.HasOne("JuanApp.Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanApp.Core.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JuanApp.Core.Models.Basket", b =>
                {
                    b.Navigation("BasketItems");
                });

            modelBuilder.Entity("JuanApp.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("JuanApp.Core.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("JuanApp.Domain.Models.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
